### ISSUE TITLE
Some resources under /api/  return status 500

### ISSUE THREAD

**Issue by jottr** [MeinGrundeinkommen/meingrundeinkommen#65]
Resources like `/api/winners` return a status code 500 when accessed via the cloudflare managed domain, `heroku.mein-grundeinkommen.de`: 

```ruby
2016-02-26T02:51:47.200998+00:00 app[web.1]: Started GET "/api/winners" for 173.245.53.61 at 2016-02-26 02:51:47 +0000
2016-02-26T02:51:48.201499+00:00 app[web.1]: Processing by Api::WinnersController#index as JSON
2016-02-26T02:51:48.430926+00:00 app[web.1]:   app/controllers/api/winners_controller.rb:8:in `index'
2016-02-26T02:51:48.427903+00:00 app[web.1]:   [1m[35mUser Load (222.2ms)[0m  SELECT id,name,avatar FROM `users`  WHERE (winner > 0)  ORDER BY winner asc
2016-02-26T02:51:48.430922+00:00 app[web.1]: 
2016-02-26T02:51:48.430924+00:00 app[web.1]: ActiveModel::MissingAttributeError (missing attribute: email):
2016-02-26T02:51:48.430934+00:00 app[web.1]: 
2016-02-26T02:51:48.430925+00:00 app[web.1]:   app/serializers/user_serializer.rb:6:in `email'
2016-02-26T02:51:48.431696+00:00 app[web.1]: Processing by ErrorsController#custom as JSON
2016-02-26T02:51:48.430927+00:00 app[web.1]: 
2016-02-26T02:51:48.205025+00:00 app[web.1]:   [1m[36mUser Load (2.4ms)[0m  [1mSELECT  `users`.* FROM `users`  WHERE `users`.`id` = 235171  ORDER BY `users`.`id` ASC LIMIT 1[0m
2016-02-26T02:51:48.432323+00:00 app[web.1]: Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
2016-02-26T02:51:48.429250+00:00 app[web.1]: Completed 500 Internal Server Error in 228ms (ActiveRecord: 224.6ms)
2016-02-26T02:51:48.432428+00:00 app[web.1]: Error during failsafe response: Missing template errors/custom with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :coffee, :haml]}. Searched in:
2016-02-26T02:51:48.432430+00:00 app[web.1]:   * "/app/app/views"
2016-02-26T02:51:48.432437+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.1.14.1/lib/action_view/rendering.rb:99:in `_render_template'
2016-02-26T02:51:48.432431+00:00 app[web.1]:   * "/app/vendor/bundle/ruby/2.3.0/gems/devise-3.2.4/app/views"
2016-02-26T02:51:48.432432+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.1.14.1/lib/action_view/path_set.rb:46:in `find'
2016-02-26T02:51:48.432435+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.1.14.1/lib/action_view/renderer/template_renderer.rb:41:in `determine_template'
2016-02-26T02:51:48.432431+00:00 app[web.1]: 
```
When the same resource is accessed from the heroku domain of `mge-rails.herokuapp.com/api/winners`, the requested json resource is returned just fine.

**Comment by jottr** [comment]
The request to `api/winners` works now. 
Requests that take longer than 30 seconds to complete are terminated by the heroku routers, and a status `500` is returned.
This is not reflected in the apps logs!
 `staging.mein-grundeinkommen.de/api/wishes/43/users` is affected by this. 
To fix this we need to optimize the requests to the database.

**Comment by jottr** [comment]
This was almost fixed, but it seems that https://github.com/MeinGrundeinkommen/meingrundeinkommen/blob/master/app/serializers/user_serializer.rb#L93 is still problematic!
